name: DevSecOps Pipeline with DAST

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  dast-testing:
    name: DAST Testing with OWASP ZAP
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Python (or relevant environment for your app)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Install dependencies (if needed for app setup)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Build or Start Application (if required)
      - name: Start the Application
        run: |
          # Misalnya untuk Flask, jika menggunakan Docker bisa disesuaikan
          nohup python app.py &  # Sesuaikan dengan aplikasi Anda

      # Install OWASP ZAP
      - name: Install OWASP ZAP
        uses: zentrick/owasp-zap-action@v1
        with:
          start_zap: true

      # Run OWASP ZAP DAST scan
      - name: Run DAST Scan with OWASP ZAP
        id: zap_scan
        run: |
          # Sesuaikan URL dengan aplikasi yang akan diuji
          zap-cli quick-scan --url=http://localhost:5000  # Sesuaikan dengan URL aplikasi Anda
          
          # Save the ZAP report to a file
          zap-cli report -o zap_report.html -f html

      # Check for Issues in the OWASP ZAP Report
      - name: Check OWASP ZAP Report for Issues
        run: |
          if grep -q "Vulnerability" zap_report.html; then
            echo "❌ OWASP ZAP found vulnerabilities in the application!"
            cat zap_report.html
            exit 1
          else
            echo "✅ No vulnerabilities found by OWASP ZAP."
          fi

      # Upload OWASP ZAP Report as Artifact
      - name: Upload OWASP ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
